version: '3.9'

services:
  backend:
    build: ./backend
    container_name: cthub-backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    container_name: cthub-frontend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
    command: npm run dev

  db:
    image: postgres:16
    container_name: cthub-db
    restart: always
    environment:
      POSTGRES_DB: cthub
      POSTGRES_USER: cthubuser
      POSTGRES_PASSWORD: cthubpass
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
